name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'

jobs:
  pr-validation:
    name: Validação PR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm run validate
      
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true
        record: false
        config: video=false,screenshotOnRunFailure=true
        wait-on: 'http://localhost:3000'
        
    - name: Start local server
      run: |
        npx http-server . -p 3000 &
        sleep 5
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pr-test-results
        path: |
          cypress/videos/
          cypress/screenshots/
          cypress/reports/
        retention-days: 7
        
    - name: Comment PR with results
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let comment = '## 🔍 Resultados dos Testes\n\n';
          
          if (fs.existsSync('cypress/reports/html/index.html')) {
            comment += '✅ **Testes executados com sucesso!**\n\n';
            comment += '📊 **Resumo:**\n';
            comment += '- Todos os testes E2E passaram\n';
            comment += '- Validação de segurança concluída\n';
            comment += '- Build validado\n\n';
            comment += '🚀 **Próximos passos:**\n';
            comment += '1. Aguarde aprovação do revisor\n';
            comment += '2. Merge será feito automaticamente após aprovação\n';
          } else {
            comment += '❌ **Alguns testes falharam!**\n\n';
            comment += '🔍 **Verifique:**\n';
            comment += '- Logs dos testes para detalhes\n';
            comment += '- Screenshots em caso de falhas visuais\n';
            comment += '- Console para erros JavaScript\n\n';
            comment += '⚠️ **Ação necessária:**\n';
            comment += 'Corrija os problemas antes do merge';
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
